""" will it work ? 

Revision ID: cf615a7a33c9
Revises: b6fb483b8934
Create Date: 2024-12-27 01:23:57.348387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf615a7a33c9'
down_revision: Union[str, None] = 'b6fb483b8934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('mahdy', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'mahdy')
    # ### end Alembic commands ###
